### ISSUE TITLE
Nothing in ./order/index.js

### ISSUE THREAD

**Issue by drekuru** [craigshoemaker/functions-custom-handlers#1]
Hey I see that you have created a function, however I am confused how this would work if you deployed it to Azure and had it run in a Function App environment. How does Azure treat **server.js**? Also I was wondering if you have any examples of setting up other external files like the configuration for using **tedious** to interact with SQL. If you have time I would love to see some examples or get some pointers on how Azure Functions interacts with files such as **config.json** or **server.js**

**Comment by craigshoemaker** [comment]
This is a work-in-progress the demo for an upcoming feature in Azure, so don't read too much into what you see here yet ;)
